version: "3.9"
name: dev_transitly_server
services:
  svc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: svc
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    ports:
      - "8001:8000"       # host:container
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data:
